Parameters:
  BucketName:
    Type: String
  MainRole:
    Type: String
  S3EmbeddingsPath:
    Type: String
  ApiToken:
    Type: String
  ModelVersion:
    Type: String
  JumpStartEmbeddingsDispatcherImage:
    Type: String
    Default: 542375318953.dkr.ecr.us-east-1.amazonaws.com/jumpstart_embedding_dispatcher:latest
  AttributionEndpoint:
    Type: String
    NoEcho: true
    Default: https://lx5eculobj.execute-api.us-east-1.amazonaws.com/v1


AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      Role: !Ref MainRole
      Timeout: 30
      Code:
        ImageUri: !Ref JumpStartEmbeddingsDispatcherImage
      Environment:
        Variables:
          attribution_endpoint: !Ref AttributionEndpoint
          api_token: !Ref ApiToken
          model_version: !Ref ModelVersion

  LambdaInvokePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "s3.amazonaws.com"
      SourceAccount: !Ref "AWS::AccountId"
      SourceArn: !Sub "arn:aws:s3:::${BucketName}"

Outputs:
  LambdaFunctionARN:
    Description: "ARN of the IAM Role"
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-IAMRoleARN"