Parameters:
  BucketName:
    Type: String
  CodeS3Bucket:
    Type: String
  EndpointLambdaCodeS3Key:
    Type: String
  PutObjectTriggerClipLambda:
    Type: String
  MainRole:
    Type: String
  S3EmbeddingsPath:
    Type: String
  ApiToken:
    Type: String

AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: Image
      Role: !Ref MainRole
      Timeout: 30
      Code:
        ImageUri: 300465780738.dkr.ecr.us-east-1.amazonaws.com/jumpstart_endpoint_lambda:latest
      Environment:
        Variables:
          endpoint: triton-gaia-ep-2023-11-20-11-04-54
          s3_bucket: !Ref BucketName
          s3_path: !Ref S3EmbeddingsPath
          api_token: !Ref ApiToken

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: LambdaApiGateway
      Description: API Gateway for Lambda function

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: jumpstart-agent  # the path of your API endpoint
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: POST  # or GET, depending on your needs
      ResourceId: !Ref ApiGatewayResource
      RestApiId: !Ref ApiGatewayRestApi
      AuthorizationType: NONE  # or your chosen authorization
      Integration:
        IntegrationHttpMethod: POST  # or GET
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations
      MethodResponses:
        - StatusCode: 200

  LambdaPermissionApiGateway:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/*/jumpstart-agent
