Parameters:
  CodeS3Bucket:
    Type: String
    Default: "jumpstart-bria-agent"
    Description: S3 Bucket where Lambda code is stored

  S3BriaBucket: 
    Type: String
    Default: "jumpstart-bria-agent-results"
    Description: Name of the BRIA bucket

  S3EmbeddingsPath: 
    Type: String
    Default: "embeddings/"
    Description: S3 Embeddings path

  MainRole:
    Type: String
    Default: "arn:aws:iam::300465780738:role/bria-agent"
    Description: Execution Role Arn

  InferenceEndpoint:
    Type: String
    Default: triton-gaia-ep-2023-11-22-12-38-24
    Description: model infrence endpoint

  ApiToken:
    Type: String
    Default: 028ff61ba99b421497880f330d625e57
    Description: model infrence endpoint



Resources:
  IAMRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://jumpstart-bria-agent.s3.amazonaws.com/iam_role_stack.yml'

  MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref S3BriaBucket

  LambdaFunctionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://jumpstart-bria-agent.s3.amazonaws.com/lambdas/api_endpoint_lambda/infra/endpoint-lambda.yml
      Parameters:
        CodeS3Bucket: !Ref CodeS3Bucket
        BucketName: !Ref S3BriaBucket
        S3EmbeddingsPath: !Ref S3EmbeddingsPath
        MainRole:  !Ref MainRole
        # MainRole:  !GetAtt IAMRoleStack.Outputs.IAMRoleARN
        ApiToken:  !Ref ApiToken
        InferenceEndpoint: !Ref InferenceEndpoint
    DependsOn: MyS3Bucket


