Parameters:
  CodeS3Bucket:
    Type: String
    Default: "jumpstart-bria-agent"
    Description: S3 Bucket where Lambda code is stored

  S3BriaBucket: 
    Type: String
    Default: "jumpstart-bria-agent-results"
    Description: Name of the BRIA bucket

  S3EmbeddingsPath: 
    Type: String
    Default: "embeddings/"
    Description: S3 Embeddings path

  InferenceEndpoint:
    Type: String
    Default: triton-gaia-ep-2023-11-22-12-38-24
    Description: model infrence endpoint

  ApiToken:
    Type: String
    Default: 028ff61ba99b421497880f330d625e57
    Description: Company API token to Bria

  ModelVersion:
    Type: String
    Default: "1.4"
    AllowedValues: ["1.4", "2.0"]
    Description: Bria model version

  MainRole:
    Type: String
    Default: "arn:aws:iam::300465780738:role/bria-agent"
    Description: Execution Role Arn


Resources:
  IAMRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://jumpstart-bria-agent.s3.amazonaws.com/iam_role_stack.yml'

  MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref S3BriaBucket
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:*
              Function: !GetAtt EmbeddingDispatcherLambdaFunctionStack.Outputs.LambdaFunctionARN
              Filter:
                S3Key:
                  Rules:
                  - Name: suffix
                    Value: .json
      DependsOn: EmbeddingDispatcherLambdaFunctionStack

  EndpointLambdaFunctionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://jumpstart-bria-agent.s3.amazonaws.com/lambdas/api_endpoint_lambda/lambda-infra.yml
      Parameters:
        BucketName: !Ref S3BriaBucket
        S3EmbeddingsPath: !Ref S3EmbeddingsPath
        MainRole:  !Ref MainRole
        # MainRole:  !GetAtt IAMRoleStack.Outputs.IAMRoleARN
        ApiToken:  !Ref ApiToken
        InferenceEndpoint: !Ref InferenceEndpoint
    DependsOn: IAMRoleStack

  EmbeddingDispatcherLambdaFunctionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://jumpstart-bria-agent.s3.amazonaws.com/lambdas/embeddings_dispatcher/lambda-infra.yml
      Parameters:
        BucketName: !Ref S3BriaBucket
        S3EmbeddingsPath: !Ref S3EmbeddingsPath
        MainRole:  !Ref MainRole
        # MainRole: !GetAtt IAMRoleStack.Outputs.IAMRoleARN
        ApiToken: !Ref ApiToken
        ModelVersion: !Ref ModelVersion
    DependsOn: IAMRoleStack